"""Type definitions for memory module."""

from .records import Skill, Rule, RuleResult, Note, HookResponse
from .hooks import HookEvent, HookEventType, Memory
from .claude import (
    # Base types
    RawHookDataBase,
    # Tool input types
    BashToolInput,
    GlobToolInput,
    GrepToolInput,
    ReadToolInput,
    WriteToolInput,
    EditToolInput,
    TaskToolInput,
    WebFetchToolInput,
    WebSearchToolInput,
    LSPToolInput,
    AskUserQuestionToolInput,
    ToolInput,
    # Tool response types
    BashToolResponse,
    GlobToolResponse,
    GrepToolResponse,
    ReadFileContent,
    ReadToolResponse,
    StructuredPatch,
    WriteToolResponse,
    EditToolResponse,
    TaskToolResponse,
    WebFetchToolResponse,
    WebSearchToolResponse,
    LSPToolResponse,
    ToolResponse,
    # Event-specific raw hook data
    NotificationRawHookData,
    UserPromptSubmitRawHookData,
    PreToolUseRawHookData,
    PostToolUseRawHookData,
    SessionStartRawHookData,
    SessionEndRawHookData,
    StopRawHookData,
    SubagentStopRawHookData,
    RawHookData,
    # Main wrapper types
    UsageInfo,
    HookData,
    HookMetadata,
    AgentHookPayload,
    # Parsing utilities
    parse_tool_input,
    parse_tool_response,
    parse_raw_hook_data,
    parse_usage,
    parse_hook_data,
    parse_hook_payload,
    # Type guards
    is_bash_input,
    is_glob_input,
    is_read_input,
    is_write_input,
    is_edit_input,
    is_task_input,
    is_pre_tool_use,
    is_post_tool_use,
    is_user_prompt_submit,
    is_notification,
    is_session_start,
    is_session_end,
    is_stop,
    is_subagent_stop,
)

__all__ = [
    # Existing exports
    "Skill",
    "Rule",
    "RuleResult",
    "Note",
    "HookResponse",
    "HookEvent",
    "HookEventType",
    "Memory",
    # Base types
    "RawHookDataBase",
    # Tool input types
    "BashToolInput",
    "GlobToolInput",
    "GrepToolInput",
    "ReadToolInput",
    "WriteToolInput",
    "EditToolInput",
    "TaskToolInput",
    "WebFetchToolInput",
    "WebSearchToolInput",
    "LSPToolInput",
    "AskUserQuestionToolInput",
    "ToolInput",
    # Tool response types
    "BashToolResponse",
    "GlobToolResponse",
    "GrepToolResponse",
    "ReadFileContent",
    "ReadToolResponse",
    "StructuredPatch",
    "WriteToolResponse",
    "EditToolResponse",
    "TaskToolResponse",
    "WebFetchToolResponse",
    "WebSearchToolResponse",
    "LSPToolResponse",
    "ToolResponse",
    # Event-specific raw hook data
    "NotificationRawHookData",
    "UserPromptSubmitRawHookData",
    "PreToolUseRawHookData",
    "PostToolUseRawHookData",
    "SessionStartRawHookData",
    "SessionEndRawHookData",
    "StopRawHookData",
    "SubagentStopRawHookData",
    "RawHookData",
    # Main wrapper types
    "UsageInfo",
    "HookData",
    "HookMetadata",
    "AgentHookPayload",
    # Parsing utilities
    "parse_tool_input",
    "parse_tool_response",
    "parse_raw_hook_data",
    "parse_usage",
    "parse_hook_data",
    "parse_hook_payload",
    # Type guards
    "is_bash_input",
    "is_glob_input",
    "is_read_input",
    "is_write_input",
    "is_edit_input",
    "is_task_input",
    "is_pre_tool_use",
    "is_post_tool_use",
    "is_user_prompt_submit",
    "is_notification",
    "is_session_start",
    "is_session_end",
    "is_stop",
    "is_subagent_stop",
]
